### ISSUE TITLE
-er suffix 

### ISSUE THREAD

**Issue by l3r8yJ** [l3r8yJ/sa-tan#35]

**Comment by 0pdd** [comment]
@l3r8yJ 2 puzzles [#38](https://github.com/l3r8yJ/sa-tan/issues/38), [#39](https://github.com/l3r8yJ/sa-tan/issues/39) are still not solved.

**Comment by 0pdd** [comment]
@l3r8yJ 2 puzzles [#95](https://github.com/l3r8yJ/oop-cop/issues/95), [#97](https://github.com/l3r8yJ/oop-cop/issues/97) are still not solved.

**Comment by 0pdd** [comment]
@l3r8yJ the puzzle [#95](https://github.com/l3r8yJ/oop-cop/issues/95) is still not solved; solved: [#97](https://github.com/l3r8yJ/oop-cop/issues/97).
