### ISSUE TITLE
Check for class name more than x symbols

### ISSUE THREAD

**Issue by h1alexbel** [l3r8yJ/sa-tan#81]
Class names with more 13 symbols reveal that code is too complex.
We should prevent it, by rejecting build if such check fails.
check: https://www.yegor256.com/2015/01/12/compound-name-is-code-smell.html

**Comment by zoeself** [comment]
@h1alexbel thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@l3r8yJ this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2024-01-07T10:50:01.946956``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by h1alexbel** [comment]
@l3r8yJ please assign me

**Comment by l3r8yJ** [comment]
@h1alexbel sure, go ahead

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#88](https://github.com/l3r8yJ/sa-tan/issues/88), [#89](https://github.com/l3r8yJ/sa-tan/issues/89) are still not solved.

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#96](https://github.com/l3r8yJ/oop-cop/issues/96), [#98](https://github.com/l3r8yJ/oop-cop/issues/98) are still not solved.
